[build]
  publish = "public"
  command = "git submodule update --init --recursive && hugo --gc --minify --baseURL $URL"

[build.environment]
  HUGO_VERSION = "0.146.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
